thoth-station/graph-sync-job

.travis.yml, .zuul.yaml, CHANGELOG.md, app.py
Starting with this release we have a Zuul-CI pipeline that:
* lints on Pull Requrest and gate/merge
=> added a zuul config, removed travis, CHANGELOG!!

openshift/cronJob-template.yaml
=> Fix deployment issues

app.py
Signed-off-by: Christoph Görn <goern@redhat.com>
=> added _info metric to carry versions

app.py, openshift/provenanceCheckerSyncJob-template.yaml
Depends-On: https://github.com/thoth-station/storages/pull/519
=> Introduce graph-sync-provenance-checker

.zuul.yaml
Signed-off-by: Christoph Görn <goern@redhat.com>
=> fixed webhhok url

openshift/provenanceCheckerSyncJob-template.yaml
Depends-On: https://github.com/thoth-station/graph-sync-job/pull/173
=> Adjust graph-sync for provenance-checker

openshift/packageExtractSyncJob-template.yaml
Depends-On: https://github.com/thoth-station/graph-sync-job/pull/179
=> Adjust graph-sync-job for package-extract

app.py, openshift/adviserSyncJob-template.yaml
=> Standardize variables and explicitly set the collection of metrics

app.py
Corrected wrong attributes for Gauge. Fixes: https://github.com/thoth-station/graph-sync-job/issues/211
=> Corrected wrong attributes

app.py
This way we do not log to Sentry, but rather retry after some time based on
the configuration.
Depends-On: https://github.com/thoth-station/storages/pull/784
Fixes: https://github.com/thoth-station/storages/issues/783
=> Introduce retry mechanism for job

app.py
=> Fix syntax error

app.py, openshift/packageExtractSyncJob-template.yaml, openshift/syncJob-template.yaml
Syncing Package Analyzer Results
Depends On: https://github.com/thoth-station/storages/pull/834
=> syncing package analyzer results

app.py, openshift/adviserSyncJob-template.yaml, openshift/dependencyMonkeySyncJob.yaml, openshift/inspectionSyncJob-template.yaml, openshift/packageExtractSyncJob-template.yaml, openshift/provenanceCheckerSyncJob-template.yaml, openshift/solverSyncJob-template.yaml, openshift/syncJob-template.yaml
=> Added time, namespace label

app.py
Fixes: https://github.com/thoth-station/amun-api/issues/210
=> Correct variable

README.rst, app.py, openshift/adviserSyncJob-template.yaml, openshift/dependencyMonkeySyncJob.yaml, openshift/inspectionSyncJob-template.yaml, openshift/packageAnalyzerSyncJob-template.yaml, openshift/packageExtractSyncJob-template.yaml, openshift/provenanceCheckerSyncJob-template.yaml, openshift/solverSyncJob-template.yaml, openshift/syncJob-template.yaml
Added Package-Analyzer Job Template
=> Add Package-Analyzer Job Template and some changes

openshift/adviserSyncJob-template.yaml, openshift/provenanceCheckerSyncJob-template.yaml
=> Standardize labels for metrics

README.rst
Fixes: https://github.com/thoth-station/graph-sync-job/issues/264
=> Updated the README

openshift/adviserSyncJob-template.yaml, openshift/inspectionSyncJob-template.yaml, openshift/packageAnalyzerSyncJob-template.yaml, openshift/packageExtractSyncJob-template.yaml, openshift/provenanceCheckerSyncJob-template.yaml, openshift/solverSyncJob-template.yaml, openshift/syncJob-template.yaml
use postgresql hostname from thoth configmap
depends-on: https://github.com/thoth-station/thoth-ops/pull/97
=> use postgresql hostname from thoth configmap

openshift/buildConfig-template.yaml, openshift/imageStream-template.yaml, openshift/syncJob-template.yaml
updated templates with annotations and param thoth-advise-value
=> updated templates with annotations and param thoth-advise-value

app.py
Depends-On: https://github.com/thoth-station/storages/pull/1220
Related: https://github.com/thoth-station/storages/issues/1219
=> Create configuration option to explictly state documents are from a local dir

app.py
Signed-off-by: Christoph Görn <goern@redhat.com>
=> just a new version

workflows/templates/sync-template.yaml
=> Add WorkflowTemplate for graph-sync to the correct location

.github/CODEOWNERS, .pre-commit-config.yaml, app.py, conf.py, observability.rst, version.py
=> Feature: service version string

Pipfile.lock
=> Update lock for release

app.py
Related-To: https://github.com/thoth-station/metrics-exporter/issues/529
=> Add metric to expose revision

app.py
Fix the reference issue of the version string
Fixes: #551
=> Fix the reference issue of version string

Pipfile.lock
=> Dependency update

Pipfile, Pipfile.lock
Removed the sphinx constraint for the dependency update
Fixes: #613 
The sphinx constraint was blocking the update, this would fix it by relaxing the constraint.
=> Removed the sphinx constraint for the dependency update

.pre-commit-config.yaml, .prow.yaml, .thoth.yaml, OWNERS
Update the precommit and owners file
=> Update the precommit and owners file

Pipfile, Pipfile.lock
Update graph-sync python dependencies
Fixes: #680
=> :pushpin: Update graph-sync python dependencies
